"use client";
import { Montserrat } from "next/font/google";
import { useContext } from "react";
import { AuthContext, AuthProvider } from "./context/auth";
import "./globals.css";

import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ToastProvider from "./components/ToastProvider";
const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: siteConfig.siteName,
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const context = useContext(AuthContext);

  return (
    <AuthProvider>
      <html lang="pt-br">
        <body className={`${montserrat.className} bg-cinza`}>
          <ToastProvider>{children}</ToastProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
