"use client";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import siteConfig from "./siteConfig";
import { useContext } from "react";
import { AuthContext, AuthProvider } from "./context/auth";

const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: siteConfig.siteName,
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const context = useContext(AuthContext)
  return (
    <AuthProvider>
      <html lang="pt-br">
        <body className={`${montserrat.className} bg-cinza`}>{children}</body>
      </html>
    </AuthProvider>
  );
}
